### PR TITLE
Allow custom post processing for batch get_picture

### PR DESCRIPTION
**Pull request by cwhetung**
* Allow custom post_processing blocks to be used with `get_picture` inside of a batch request

### CODE REVIEW

**Comment by cwhetung** [comment]
As far as I can see, currently any custom blocks passed to `get_picture` inside of a batch request are ignored because only the `graph_call` post_processing block was being belayed for the batch request

**Comment by cwhetung** [comment]
Hey @arsduo. just checking in to see if you had a chance to look this over?

**Comment by arsduo** [comment]
Hey — sorry I let this sit so long. That's a really good catch. Merging in now.

**Comment by cwhetung** [comment]
Awesome! It was no problem, thanks!

**Pull request merged**
