### PR TITLE
Batch with support for recursive calls

### PR DESCRIPTION
**Pull request by dmitchell**
So, this seems to work fine. I'll kill the other PR and see if I can duplicate the weird recursion error in my system.

### CODE REVIEW

**Comment by arsduo** [comment]
Awesome! I'll review this this weekend or next week, ditto for the limits PR to come.

**Comment by dmitchell** [comment]
I duplicated the erroneous compounding of submissions on recursion error. I'll try to ensure i understand it today. idk if I can generate a unit test to duplicate it tho.

**Comment by dmitchell** [comment]
The error was due to using a singleton as a proxy to the graph_batch_api and the singleton not being threadsafe. I had intended to remove that singleton. Now I have.

I did notice that you refactored graph_batch_api in a way which makes it impossible for me to merge my changes for limiting batch size. I'll try to re-implement it on your new impl sometime.

I also found out that FB sometimes responds w a subset of the batch rather than processing and responding to the whole batch. I changed my fork to requeue any unresponded batch ops. I'm a bit worried about doing that in general bc if someone uses `name` and `result` and the code is chopping the batches and mixing the order, all sorts of f'ups will occur.

**Comment by arsduo** [comment]
Thanks for putting that to Facebook! I look forward to hearing what they say.

Apologies for the merge problems. I'd been working on a big set of changes around all the APIs, with bad timing. I'll see if I can apply your changes to the current state and push up a commit you can merge in so you don't have to deal with it.

**Pull request merged**
