### PR TITLE
Bump GHA action plugins to avoid deprecation warnings

### PR DESCRIPTION
**Pull request by zenspider**
simple bump, removes old node warnings

### CODE REVIEW

**Comment by ylecuyer** [comment]
Could you show an example of the deprecation warning and where you see them, I can't find them in the CI logs

**Comment by ylecuyer** [comment]
Commented to fast, I found them here: https://github.com/arsduo/koala/actions/runs/8916001798

Screenshot_2024-05-02_01-19-43

**Comment by ylecuyer** [comment]
Could you also bump paambaati/codeclimate-action to v6, this way we can clear all deprecation warning at once. I tried to update the PR directly but looks like it is forbiden by the org, or the allow maintainer to edit option on the PR isn't enabled

**Comment by zenspider** [comment]
done!

sorry I missed that one... we yanked codeclimate from our fork because we're forbidden from using that action.

**Comment by ylecuyer** [comment]
Could you add this to the changelog please as the PR is still not editable by maintainers I can't do it:

```patch
diff --git a/changelog.md b/changelog.md
index 8a22e01..1868d01 100644
--- a/changelog.md
+++ b/changelog.md
@@ -19,6 +19,7 @@ Testing improvements:
 
 * Fix CI for ruby 3.4 ([#688](https://github.com/arsduo/koala/pull/688))
 * Add latest rubies to CI ([#687](https://github.com/arsduo/koala/pull/687))
+* Bump GHA action plugins to avoid deprecation warnings ([#689](https://github.com/arsduo/koala/pull/689))
 
 Others
 ```

**Comment by zenspider** [comment]
pushed with requested edits

**Pull request merged**
