### PR TITLE
Exposing raw facebook headers

### PR DESCRIPTION
**Pull request by pawandubey**
This is for the issue #522 

Haven't added/modified tests yet because I first want to test feasibility of this PR. We internally use 2.4.0, hence the request against the latest 2.x release.

What are your thoughts on this? @arsduo

### CODE REVIEW

**Comment by pawandubey** [comment]
Okay, I have fixed the tests too now. They still won't pass because of the SimpleCov issue. But I resolved that issue locally and all the specs pass alright.

**Comment by arsduo** [comment]
Thanks for the pull request! I like the idea of adding the headers to the graph collection (which would also resolve #337), but I think we can implement it more smoothly than returning a tuple of `[body, headers]`. 

In 3.0, I've been refactoring the relation between the `graph_call` and `api` methods. Now that the REST API is gone, `graph_call` and the Batch API are the only two users of `api`; my plan is to have `api` return a `Koala::HTTPService::Response` object, giving `graph_call` full access to the headers and everything else. 

From that point it'd be easy to implement your change, adding the headers (or perhaps better the whole response object) to GraphCollection. For non-GraphCollection responses people can always request the raw response itself.

Would you be open to reimplementing this on top of 3.0 once I push that change up? If not, I can.

**Comment by arsduo** [comment]
I've just pushed up the PR to have API#api return a Koala::HTTPService::Response object, which means API#graph_call now has easy access to the headers to pass to GraphCollection. 

If you have time/interest in implementing that soon and want to take that on, that would be awesome. Otherwise I'll do it this weekend.

Thanks again!

**Comment by pawandubey** [comment]
@arsduo I came up with the tuple solution simply because there was no clean way of integrating headers without a major refactoring in the 2.x branch. I saw your PR and it seems to be much easier to make the headers work with the GraphCollection now. I will take a stab at it if I get free time within the next two days. Do you think this can be backported to the 2.x branch though?

**Comment by arsduo** [comment]
Unfortunately I don't think it'd be possible to backport this to 2.x -- the changes and refactors to get the code to the point where the change becomes easy are basically what differentiates 2.x from 3.0. 

That said, 3.0 should not be a big change for most users -- if you're not using HTTPService.make_request or API#api directly, nothing should change. I'd actually appreciate some testing and feedback on the new version, if you have a chance to try it out!

**Comment by pawandubey** [comment]
We are using a custom `HTTPService` module with an overriden `make_request` method, so I guess that qualifies as incompatible? I'll have to take a look at the documentation for the changes I think.

**Comment by arsduo** [comment]
Oh, interesting! I'd love to hear more if you're willing to share. What customizations did you have to make? What needs did your project have? 

Obviously there are limits to how customizable we can make Koala, but if at all possible it would be great to be able to support most people's need for different behavior directly. Understanding how people have used and changed the gem can help me guide future changes.

**Comment by pawandubey** [comment]
We override it to wrap around the actual call with code for sending events to our monitoring service (datadog). We record each request, where it came from and if it was successful. The actual code is very simple but allows us to keep a check on some reliability issues. The current solution actually works pretty well for us.

**Comment by arsduo** [comment]
Interesting! I'd be open to a pull request that would allow that (maybe via
an optional block?) if you're interested in doing that.

**Comment by arsduo** [comment]
Actually, take a look at the [newest version of HTTPService](https://github.com/arsduo/koala/blob/master/lib/koala/http_service.rb). It takes a (new) `Koala::HTTPService::Request` object and returns a `Koala::HTTPService::Response` object. Could you potentially wrap that as is and log the data from those two objects? That might allow you to upgrade without needing to duplicate the internals of the HTTPService.

**Comment by pawandubey** [comment]
Hey, sorry for the absence. I saw the new make_request version. So basically we do the override right now because our application calls either `get_object` or `put_object` a total of 150 times from different places. So it is inefficient to instrument every individual call. Overriding the method allowed us to do it at one central place, reducing a lot of technical debt. I don't think the current implementation allows us to do that.

**Comment by arsduo** [comment]
Oh, I wasn't suggesting that you instrument each individual call. Rather something like this:

```ruby
class YourHTTPService
  def self.make_request(request)
    t = Time.now
    response = HTTPService.make_request(request)    
    log_some_data(request, response, Time.now - t, other_data)
    response
  end
end

Koala.http_service = YourHTTPService
```

If I understand what you're doing right (which I might not) that would allow you to log all the data about the request in version 3.0 without having to replicate the whole HTTPService class.

**Comment by arsduo** [comment]
About this PR: let me know if you think you'll have time to implement similar changes for version 3.0 this week. Otherwise I can take care of it this weekend -- I'd like to release a new-final beta of 3.0 soon.

Thanks again!

**Comment by pawandubey** [comment]
@arsduo That's actually what we are doing right now. Heck, here is the actual code:

````ruby
module KoalaInstrumenter
  include Koala::HTTPService

  def self.is_batch_call?(args)
    return args.key? 'batch'
  end

  def self.make_request(path, args, verb, options = {})
    # before_stuff
    # make the request
    job_name = ENV['job_name'] || 'web_app'
    result = Koala::HTTPService.make_request(path, args, verb, options)
    tags = ["verb:#{verb}", "job_name:#{job_name}"]
    # we do batch call in batches of 50.
    increment = is_batch_call?(args) ? 50 : 1
    # return the body of the result as a Koala::Response object
    StatsdIntegration::StatsD.send_event_to_statsd(
      'all', { measurement: 'koala_call', tags: tags, value: increment })
    if result.status != 200
      StatsdIntegration::StatsD.send_event_to_statsd(
      'all', { measurement: 'koala_call_error', tags: tags })
    end
    result
  end

  def self.encode_params(params_hash)
    Koala::HTTPService.encode_params(params_hash)
  end
end

Koala.http_service = KoalaInstrumenter unless Rails.env.test?
````

As you can see it's very similar to your example. Is your example a valid use of the 3.x branch? Or does it need the required changes to actually support that use case?

**Comment by arsduo** [comment]
Hahaha, cool! You should be able to do what you're doing with 3.0 with
relatively minor changes — it'll take a Request object instead of the four
arguments and you can access the raw_verb and raw_args methods where you're
currently using args and verb.

**Comment by pawandubey** [comment]
Closing this in favour of #589

**Pull request closed without merging**
